name: Run CI
on:
  push:
    branches-ignore:
      - develop
      - release/**
  pull_request:

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://npm.pkg.github.com'
    - name: npm install, build, and test
      run: |
        npm install
        npm run build:release
        npm test
