name: Create snapshot release
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:release
      - name: Run tests
        run: npm test

  deploy:
    needs:
      - test
    runs-on: macos-11
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: npm install
      - name: Publish snapshot release
        run: ./.build/pre-release.sh
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}