name: Create tagged release
on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:release
      - name: Run tests
        run: npm test

  deploy:
    needs:
      - test
    runs-on: macos-11
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: npm install
      - name: Publish tagged release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"
